### ISSUE TITLE
ErrTableNotFound

### ISSUE THREAD

**Issue by jonbonazza** [tsuna/gohbase#42]
I am doing a series (read: thousands) of PUT operations on a table that **does** exist (basically, I am scanning one table, and for each row, doing a small transform and putting into another table). Sometimes, the PUT operation fails and I get the error "table not found" from the client. The rows that this operation fails on are different every time the task is run.

I have narrowed down the error to the following function:
```go
// metaLookup checks meta table for the region in which the given row key for the given table is.
func (c *client) metaLookup(ctx context.Context,
	table, key []byte) (hrpc.RegionInfo, string, uint16, error) {

	metaKey := createRegionSearchKey(table, key)
	rpc, err := hrpc.NewGetBefore(ctx, metaTableName, metaKey, hrpc.Families(infoFamily))
	if err != nil {
		return nil, "", 0, err
	}

	resp, err := c.Get(rpc)
	if err != nil {
		return nil, "", 0, err
	}
	if len(resp.Cells) == 0 {
		return nil, "", 0, TableNotFound
	}

	reg, host, port, err := region.ParseRegionInfo(resp)
	if err != nil {
		return nil, "", 0, err
	}
	if !bytes.Equal(table, fullyQualifiedTable(reg)) {
		// This would indicate a bug in HBase.
		return nil, "", 0, fmt.Errorf("wtf: meta returned an entry for the wrong table!"+
			"  Looked up table=%q key=%q got region=%s", table, key, reg)
	} else if len(reg.StopKey()) != 0 &&
		bytes.Compare(key, reg.StopKey()) >= 0 {
		// This would indicate a hole in the meta table.
		return nil, "", 0, fmt.Errorf("wtf: meta returned an entry for the wrong region!"+
			"  Looked up table=%q key=%q got region=%s", table, key, reg)
	}
	return reg, host, port, nil
}
```
Specifically, the block:
```go
if len(resp.Cells) == 0 {
	return nil, "", 0, TableNotFound
}
```

It looks like, for some reason, no results are being returned when trying to retrieve the metadata for a region. What situations might cause this issue? I'm beginning to think this is another environment related issue, but wanted to be sure before I go yelling at our ops team. :)

**Comment by Timoha** [comment]
Sounds pretty weird, which commit of master branch of gohbase are you on? I fixed some bugs recently that might be relevant (https://github.com/tsuna/gohbase/commit/e7933c09a092443ade5610de9d0043f7604c58ac and https://github.com/tsuna/gohbase/commit/131514f4f51b1c877391a178f1db8aa47595786b). 

Also, if you are on the latest master, it might be useful to enable `Debug` logging level and check for https://github.com/tsuna/gohbase/blob/master/rpc.go#L191 line right before `TableNotFound` error happens to know which region it's actually looking up.

**Comment by Timoha** [comment]
FYI, if you are going to update to latest master, make sure to update this dependency package as well: https://github.com/cznic/b 
Otherwise it will compile, but you'll have unexpected behavior.

**Comment by jonbonazza** [comment]
@Timoha I updated to master, however, I did not update the cznic/b lib. I'll try that. Otherwise with master I see the same thing. I will try enabling debug logging and get back to you.

**Comment by jonbonazza** [comment]
@Timoha so I updated cznic/b and enabled debug logging. I still see the error, but now it's preceded with 
"hbase:meta does not know about this table/key" err="table not found" key="<redacted>" table=<redacted>."

**Comment by Timoha** [comment]
Do you have a line somewhere above that says something like:
```
"looking up region" table=." key=""
```
Also, not sure what `table=."` means. Are you sure that you constructing your put query correctly with providing non-empty table/row?

**Comment by jonbonazza** [comment]
Yes, I see that line as well, and the table and key matches what's in the "does not know about this table/key" error line.

**Comment by jonbonazza** [comment]
Actually wait, that's incorrect. I see that line for the successful rows, but that line is abesent on the rows that failed.

**Comment by jonbonazza** [comment]
Also, the table=. Was a markdown screw up on my part. I edited the comment to fix it. A valid table and key were included in the log line, but i was trying to redact them.

**Comment by Timoha** [comment]
> but i was trying to redact them

Oh I see

Do you start with an empty table for puts every time? If you have access to hbase shell, could you check by scanning `hbase:meta` table how many regions your table has after the error happens. Maybe gohbase handles splits incorrectly in some weird edge case (it's been fine on our cluster tho). 

Also please tell me your exact hbase version (maybe some meta formatting issue)

**Comment by jonbonazza** [comment]
So basically, I took a page out of graphics programming's book and have a "back" table and a "front" table. The "front" table is considered "live", while the back table is a buffer for writing. First thing I do when I kick off the job is truncate the back table. Then, I scan the source table, and for each row, run a small transform job on the key and value, and then put the  transformed key and value into the back table. Once the scan is complete and all hte new data is in the back table, I swap the front and back table, so that the new data becomes "live".

Most of the puts work, however a few of the puts fail with the above error. The puts the fail are different every time and there doesn't seem to be any pattern to them that I can tell.

We are using Cloudera Hadoop 5.6.1 which according to [this page](https://www.cloudera.com/documentation/enterprise/release-notes/topics/cdh_vd_cdh_package_tarball_56.html) is equivalent to hbase 1.0.0.

I will need to do some investigation on the hbase:meta table and get back to you.

**Comment by Timoha** [comment]
So are your "back" and "front" tables created on demand? Like when you swap from "front" table to "back" table, do you create a new "back" table?

**Comment by jonbonazza** [comment]
No, the tables are created ahead of time.

Also, after some experimenting, it seems this is only an issue in one of our environments. In other environments, it seems to work fine, so I am leaning to chalk this up to something screwed up with the HBase cluster in that environment. We did have some region server crashes the other day and these issues started to present themselves around that time, so maybe something is still out of wack there.

**Comment by Timoha** [comment]
Ha ok, do you might closing this issue for now and we can reopen it if it happens again?

**Comment by jonbonazza** [comment]
Sure. Closing for now.

**Comment by Timoha** [comment]
This is probably related to this issue in HBase: https://issues.apache.org/jira/browse/HBASE-18066

**Comment by jonbonazza** [comment]
@timoha interesting... That does sound like the situation I was seeing. I haven't noticed it in a while though.

**Comment by timoha** [comment]
the issue on hbase has been resolved, waiting for 1.3.2 to become available.
